---

- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mariadb_root_hosts
  changed_when: false

- name: Update MySQL root password for localhost root account.
  shell: >
    mysql -u root -NBe
    'SET PASSWORD FOR "root"@"{{ item }}" = PASSWORD("{{ mariadb_root_password }}");'
  with_items:
    - "{{ mariadb_root_hosts.stdout_lines }}"
  when: mariadb_install_packages.changed == True

- name: Copy .my.cnf file with database root credentials.
  template:
    src: user-my.cnf.j2
    dest: "{{ ansible_user_dir }}/.my.cnf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gecos }}"
    mode: 0600

- name: Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mariadb_anonymous_hosts
  changed_when: false

- name: Remove anonymous MariaDB users.
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: mariadb_anonymous_hosts.stdout_lines

- name: Remove MariaDB test database.
  mysql_db:
    name: test
    state: absent
