---

- name: Update apt cache to get PHP packages.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-pear
    - php-common
    - php-curl
    - php-dev
    - php-fpm
    - php-gd
    - php-json
    - php-mcrypt
    - php-mysql

- name: Make www-data own cgi-bin.
  file:
    path: "/usr/lib/cgi-bin"
    state: directory
    owner: www-data
    group: www-data

- name: Touch php-fpm cgi-bin file.
  file:
    path: "/usr/lib/cgi-bin/php7.0-fcgi"
    state: touch
    owner: www-data
    group: www-data

- service: name=apache2 state=restarted

# missing uploadprogress from pecl
#pecl channel-update pecl.php.net
#pecl install uploadprogress
#touch /etc/php.d/uploadprogress.ini
#echo extension=uploadprogress.so > /etc/php.d/uploadprogress.ini
