---

- name: Update apt cache to get PHP packages.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - composer
    - libapache2-mod-php
    - php-pear
    - php-common
    - php-curl
    - php-dev
    - php-gd
    - php-json
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - pkg-php-tools

- name: "Update pecl channels."
  command: pecl channel-update pecl.php.net

- name: "Install uploadprogress using pecl."
  command: pecl install uploadprogress

- name: "Activate uploadprogress.ini."
  lineinfile:
    dest: /etc/php/7.0/mods-available/uploadprogress.ini
    line: "extension=uploadprogress.so"
    create: yes
    state: present

- name: Increase PHP memory limit to 256M.
  lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    state: present
    regexp: "^memory_limit "
    line: "memory_limit = 256M"
