---

- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: "apt-get update"
      raw: apt-get update

    - name: 'Install Python.'
      raw: apt-get -y install python python-simplejson aptitude

- hosts: all
  become: yes

  roles:
    - system
    - apache
    - php
    - mariadb
    - drupal
